/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AIModelChoose: typeof import('./src/components/AIModelChoose.vue')['default']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElOptionGroup: typeof import('element-plus/es')['ElOptionGroup']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    PagesChoose: typeof import('./src/components/PagesChoose.vue')['default']
    PromptInput: typeof import('./src/components/PromptInput.vue')['default']
  }
}
