import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import * as fs from 'fs';

// 确保 dist 目录存在
if (!fs.existsSync("dist")) {
	fs.mkdirSync("dist");
}

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

// 复制 manifest.json 和 styles.css 到 dist 目录
fs.copyFileSync("manifest.json", "dist/manifest.json");
if (fs.existsSync("styles.css")) {
	fs.copyFileSync("styles.css", "dist/styles.css");
}

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		...builtins],
	format: "cjs",
	target: "es2016",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "dist/main.js",
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
